services:
  postgres:
    image: postgres:17.6-alpine
    container_name: pepperminto_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pepperminto
      POSTGRES_PASSWORD: pepperminto
      POSTGRES_DB: pepperminto
    volumes:
      - pepperminto_postgres:/var/lib/postgresql/data
    expose:
      - 5432

  pepperminto:
    image: delilahsaturn/pepperminto:latest
    container_name: pepperminto
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: .env
    environment:
      DB_USERNAME: pepperminto
      DB_PASSWORD: pepperminto
      DB_HOST: postgres
      SECRET: ${SECRET}
      UPLOADS_DIR: /app/uploads
      DATABASE_URL: postgresql://pepperminto:pepperminto@postgres:5432/pepperminto
    ports:
      - "3121:3000"
      - "3122:3001"
    volumes:
      - pepperminto_uploads:/app/uploads

  knowledge-base:
    image: delilahsaturn/pepperminto-knowledge-base:latest
    container_name: pepperminto_knowledge_base
    restart: unless-stopped
    depends_on:
      - pepperminto
    env_file: .env
    environment:
      API_URL: http://pepperminto:3001
      BASE_URL: ${BASE_URL-}
      DASHBOARD_URL: ${DASHBOARD_URL-}
      KNOWLEDGE_BASE_URL: ${KNOWLEDGE_BASE_URL-}
      NODE_ENV: production
    ports:
      - "3124:3000"

volumes:
  pepperminto_postgres:
  pepperminto_uploads:
